### ISSUE TITLE
Docs for keymap seem very broken

### ISSUE THREAD

**Issue by sdondley** [ckipp01/stylua-nvim#4]
First, it has unmatched quotes:

`buf_set_keymap("n", "<leader>f", "<cmd>lua require("stylua-nvim").format_file()<CR>', opts)`

Second, it just doesn't seem to work at all: See https://stackoverflow.com/questions/71212000/attempt-to-call-global-buf-set-keymap-a-nil-value-when-trying-to-load-key/71212199#71212199

I know zilch about neovim with lua so can't supply a patch. Just calling this to your attention.

**Comment by ckipp01** [comment]
Thanks for the heads up @sdondley. Should be corrected now.
